### ISSUE TITLE
Job call

### ISSUE THREAD

**Issue by huggy06** [spatie/laravel-stripe-webhooks#48]
I understand,  here is teh exception

Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to App\Jobs\StripeWebhooks\HandlePaymentFailedInvoice::__construct() must be an instance of App\Jobs\StripeWebhooks\WebhookCall, instance of Spatie\WebhookClient\Models\WebhookCall given, called in E:\Walky\walky\vendor\spatie\laravel-stripe-webhooks\src\ProcessStripeWebhookJob.php on line 28 in E:\Walky\walky\app\Jobs\StripeWebhooks\HandlePaymentFailedInvoice.php:25
Stack trace:

And the code

use Illuminate\Bus\Queueable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Spatie\WebhookClient\Models\WebhookCall;

class HandlePaymentActionRequiredInvoice implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /** @var \Spatie\WebhookClient\Models\WebhookCall */
    public $webhookCall;
    
    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct(WebhookCall $webhookCall)
    {
        $this->webhookCall = $webhookCall;
    }

    /**

**Comment by drbyte** [comment]
Two things:

1. The stack trace you posted relates to `E:\Walky\walky\app\Jobs\StripeWebhooks\HandlePaymentFailedInvoice.php:25`, but the code you posted is for `class HandlePaymentActionRequiredInvoice`

2. The error message in your stack trace says: 
```text
Argument 1 passed to App\Jobs\StripeWebhooks\HandlePaymentFailedInvoice::__construct() 
must be an instance of App\Jobs\StripeWebhooks\WebhookCall, 
instance of Spatie\WebhookClient\Models\WebhookCall given
```
But in the code you posted you are importing `use Spatie\WebhookClient\Models\WebhookCall;` instead of `App\Jobs\StripeWebhooks\WebhookCall`
